version: 2.10.1.{build}
os: Visual Studio 2019
configuration: Debug
platform: Any CPU

branches:
  only:
  - master

skip_tags: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: XvmOROcqgidalZg23H16UjDbAxIMkpuVXwKKPEp0bq3W5J2av35X1BsZvClM25JX

install:
  - cmd: git submodule update --init --recursive
  - cmd: dotnet restore submodules\MimeKit\MimeKit.sln
  - cmd: dotnet restore MailKit.sln

build:
  project: MailKit.sln
  verbosity: minimal

test_script:
- ps: >-
    $NUnitConsoleRunner = Join-Path $Home ".nuget\packages\nunit.consolerunner\3.11.1\tools\nunit3-console.exe"

    $Coveralls = Join-Path $Home ".nuget\packages\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe"

    $OpenCoverDir = Join-Path $Home ".nuget\packages\opencover\4.6.519\tools"

    $OpenCoverProfiler32 = Join-Path $OpenCoverDir "x86\OpenCover.Profiler.dll"

    $OpenCoverProfiler64 = Join-Path $OpenCoverDir "x64\OpenCover.Profiler.dll"

    $OpenCover = Join-Path $OpenCoverDir "OpenCover.Console.exe"

    $OutputDir = "UnitTests\bin\Debug\net48"

    & regsvr32 $OpenCoverProfiler32

    & regsvr32 $OpenCoverProfiler64

    & $OpenCover -filter:"+[MailKit]* -[MimeKit]* -[UnitTests]*" -target:"$NUnitConsoleRunner" -targetdir:"$OutputDir" -targetargs:"--domain:single UnitTests.dll" -output:opencover.xml

    & $Coveralls --opencover -i opencover.xml --repoToken $Env:COVERALLS_REPO_TOKEN --useRelativePaths --basePath $OutputDir --commitId $Env:APPVEYOR_REPO_COMMIT --commitBranch $Env:APPVEYOR_REPO_BRANCH --commitAuthor $Env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $Env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $Env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $Env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
